language: elixir
elixir:
  - 1.15.7
otp_release:
  - 26.1.1
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix compile
  - MIX_ENV=test mix compile
script:
  - mix test
